**Creating a Database**

In [ ]:
import numpy as np
import pandas as pd

**Creating a database**

In [ ]:
data = {
    'Name': ['john', 'Anna', 'Peter', 'Linda'],
    'city': ['New York', 'Paris', 'Berlin', 'London'],
    'Age': [28, 34, 29, 42],
    'salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [28]:
df

    Name      city  Age  salary
0   john  New York   28   65000
1   Anna     Paris   34   70000
2  Peter    Berlin   29   62000
3  Linda    London   42   85000

In [ ]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [ ]:
columns = ['Name', 'Age', 'City', 'Salary']
df2 = pd.DataFrame(data_list, columns=columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [27]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**Selection and indexing of dataframe**

In [31]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [38]:
df2[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

**Creating new columns**

In [39]:
df2["designation"] = ["doctor","Eng","doctor","Eng"]

In [40]:
df2

    Name  Age      City  Salary designation
0   John   28  New York   65000      doctor
1   Anna   34     Paris   70000         Eng
2  Peter   29    Berlin   62000      doctor
3  Linda   42    London   85000         Eng

In [43]:
df2.drop("designation", axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [46]:
df2

    Name  Age      City  Salary designation
0   John   28  New York   65000      doctor
1   Anna   34     Paris   70000         Eng
2  Peter   29    Berlin   62000      doctor
3  Linda   42    London   85000         Eng

In [49]:
df2.drop("designation", axis=1, inplace=True)

In [50]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

removing cloumns

In [60]:
df2.drop(["City", "Salary"], axis=1)

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [61]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [62]:
df2.drop([0,1], axis=0)

    Name  Age    City  Salary
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [63]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**Selectingn rows**

In [64]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [67]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [68]:
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

Selectiong subset of rows and columns

In [75]:
df.loc[[0,1]] [["Name","Age"]]

   Name  Age
0  john   28
1  Anna   34

In [76]:
df

    Name      city  Age  salary
0   john  New York   28   65000
1   Anna     Paris   34   70000
2  Peter    Berlin   29   62000
3  Linda    London   42   85000

In [78]:
df.loc[[2,3]] [["Name", "city"]]

    Name    city
2  Peter  Berlin
3  Linda  London

**Conditional Selection**

In [88]:
df

    Name      city  Age  salary
0   john  New York   28   65000
1   Anna     Paris   34   70000
2  Peter    Berlin   29   62000
3  Linda    London   42   85000

In [80]:
# i only want to see people whose age is above 30

In [89]:
df2[df["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [92]:
df2[(df2["Age"] > 30) & (df2["City"] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000