**Pandas Series**



---
creating series

In [1]:
import numpy as np
import pandas as pd

In [8]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

In [9]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [10]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [11]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [12]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64